### ISSUE TITLE
Rest inkonsistente Response von Customer und Product

### ISSUE THREAD

**Issue by mtinner** [marzelwidmer/price-service#9]
http://localhost:8080/api
```json
{
  "_links": {
    "customers": {
      "href": "http://localhost:8080/api/customers"
    },
    "self": {
      "href": "http://localhost:8080/api"
    }
  }
}
```

für POST http://localhost:8080/api/customers
```json
{
  "someStuff"
  },
  "_links": {
    "self": {
      "href": "http://localhost:8080/api/customers/3"
    },
    _"list_products": {
      "href": "http://localhost:8080/api/customers/3/products"
    },
    _"create_product": {
      "href": "http://localhost:8080/api/customers/3/products"
    },
    "create_deeplink": {
      "href": "http://localhost:8080/api/customers/3/deeplink"
    }
  }
}
```

Vorschlag Response für
für POST http://localhost:8080/api/customers
```json
{
  "someStuff"
  },
  "_links": {
    "self": {
      "href": "http://localhost:8080/api/customers/3"
    },
    _"products": {
      "href": "http://localhost:8080/api/customers/3/products"
    },
    "create_deeplink": {
      "href": "http://localhost:8080/api/customers/3/deeplink"
    }
  }
}
```

create_product & list_products unter http://localhost:8080/api/customers/3/products

**Comment by marzelwidmer** [comment]
Die frage ist ob man die links für "list_products" und  "create_product" zusammen führe könne unter "product" ?  

Wenn ja verstehe ich nicht warum, denn die links dahinter sollten für das UI irrelevant sein in diesem use case jetzt sind sie evtl. die selben endpoint dies muss aber nicht sein. man sollte dich nicht auf die URL's beziehen sondern an den link Namen.
